### ISSUE TITLE
Pip install pysubgroup doesn't work

### ISSUE THREAD

**Issue by tmerrittsmith** [flemmerich/pysubgroup#1]
Hey,

I'm trying to install pysubgroup using pip. The command runs ok, but it doesn't build the package. The only file I'm left with in my site-packages folder is `pysubgroup-0.5.4.dist-info`.

Any ideas?

**Comment by flemmerich** [comment]
Hi,

I hopefully fixed this in the new version (0.6); Problem was a misconfigured setup.py
