### ISSUE TITLE
RuntimeError: Beam width in the beam search algorithm is smaller than the result set size

### ISSUE THREAD

**Issue by geocarvalho** [flemmerich/pysubgroup#35]
Thanks to make the project open. As it looks inactivated, just registering that when the number of subgroups found is less than the set size used it returns an error.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-9139187cbd91> in <module>
     13     depth=100,
     14     qf=ps.WRAccQF())
---> 15 result = ps.BeamSearch().execute(task)
     16 result_df = result.to_dataframe()
     17 result_df.to_csv("../download_geo/GSE51032/GSE51032_beamsearch_result_dp100_sz40_nodiagnosis.csv", index=False)

~/miniconda2/envs/python3/lib/python3.8/site-packages/pysubgroup/algorithms.py in execute(self, task)
    277         # check if beam size is to small for result set
    278         if self.beam_width < task.result_set_size:
--> 279             raise RuntimeError('Beam width in the beam search algorithm is smaller than the result set size!')
    280 
    281         task.qf.calculate_constant_statistics(task.data, task.target)

RuntimeError: Beam width in the beam search algorithm is smaller than the result set size!
```

`pysubgroup                0.7.2                    pypi_0    pypi`

**Comment by mgbckr** [comment]
I usually just adjust the beam width to a higher value accordingly and the error goes away. Do you have any specific reason not to do so on your end?

**Comment by geocarvalho** [comment]
Thank you for the quick answer @mgbckr. I thought I should decrease the `result_set_size` for this case, am I wrong? My problem is that I have a large dataset that takes 2 days to return an error instead of the result (even being smaller than the one set size).

**Comment by flemmerich** [comment]
Yes, you can either decrease the `result_set_size` or increase the beam_width for the BeamSearch, e.g., by setting the `beam_width_adaptive` parameter  to True when initilaizing the algorithm.

Apart from that, two days runtime for a BeamSearch is really a lot. May I ask what the size of your search_space is? It might be that you include a lot of irrelevant values.

**Comment by geocarvalho** [comment]
Thank you @flemmerich, this code to set the `beam_width_adaptive` is correct?

```
task = ps.SubgroupDiscoveryTask (
    df, 
    target, 
    searchspace, 
    result_set_size=40, 
    depth=100,
    qf=ps.WRAccQF())
result = ps.BeamSearch(beam_width_adaptive=True).execute(task)
```

The length of my `searchspace` is 513756, it is molecular biology data.

**Comment by geocarvalho** [comment]
Worked fine adding `beam_width_adaptive=True` to `BeamSearch`.
Thank you, guys.
